# Default values for omar-cucumber-backend-test.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 1

appName: omar-cucumber-backend-test

global:
  dockerRepository: nexus-docker-private-group.ossim.io
  imagePullSecret:
    registry: null
    username: null
    password: null
  hostname: omar-dev.ossim.io

  createIngress: true
  useTls: false
  useTLSClientAuth: false
  sslCertSecretName: null
  authSslCertSecretName: null

  createImagePullSecret: true
  useImagePullSecret: true

# These variables can be overridden because of the use of the 'pluck' function:
# - createIngress
# - useTls
# - useTlsClientAuth
# - createImagePullSecret

resources:
  limits:
    cpu: 500m
    memory: 1000Mi
  requests:
    cpu: 4m
    memory: 500Mi
    
image:
  name: omar-cucumber-backend-test
  tag: dev
  pullPolicy: Always

ingressPath: /omar-cucumber-backend-test
ingressRewriteTarget: /$1
internalPort: 8080
externalPort: 8080

livenessProbe:
  failureThreshold: 5
  path: /backend-test
  initialDelaySeconds: 60
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 3

terminationGracePeriodSeconds: 30

envVars:
  JAVA_OPTS: "-server -Xms256m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1 -XX:+CMSClassUnloadingEnabled -XX:+UseGCOverheadLimit -Djava.awt.headless=true -XshowSettings:vm -Djava.security.egd=file:/dev/./urandom"
