/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package omar.cucumber.backend.test

import omar.cucumber.backend.test.FeatureFiles
import omar.cucumber.backend.test.CucumberTest
import omar.cucumber.backend.test.TomcatStart

class Application {
    static void main(String[] args) {

        FeatureFiles featureFiles = new FeatureFiles()
        featureFiles.create()

        if (System.getenv("runEnv") == "local")
        {
            CucumberTest backend = new CucumberTest()
            backend.startTest()
        } else {
            TomcatStart tomcat = new TomcatStart()
            tomcat.startServer()
        }
    }
}